### PR TITLE
Modification for simplified compilation for beginners

### PR DESCRIPTION
**Pull request by Coppelia**
in order to be able to compile without needing the stubsGen if the stubs are already in place. In the versions distributed with V-REP, I will always place the built stubs (stubs.h and stubs.cpp) in the /include and /src folders)

### CODE REVIEW

**Comment by fferri** [comment]
nice! we could use a similar thing for (not) generating the bundled reference.html file containing the API docs

**Comment by Coppelia** [comment]
Exactly. if we can do something similar for the doc, that would be perfect!

**Comment by Coppelia** [comment]
and please also add link_directories("/opt/ros/kinetic/lib") to that file

**Comment by fferri** [comment]
Solved in a95a2c1

**Comment by fferri** [comment]
This issue was moved to CoppeliaRobotics/v_repExtRosInterface#3

**Pull request closed without merging**
